### ISSUE TITLE
Build Fails with the following error

### ISSUE THREAD

**Issue by pomland-94** [bitnami/minideb#143]
Hey,
when I try to build a Debian Bullseye Image withe the following Command:

`make build bullseye`

the build Fails at the Stage:

`Building bitnami/minideb:buster-arm64`

with the following error:

`Setting up qemu static in chroot
Cannot find aarch64 qemu static. Aborting...
make: *** [Makefile:27: build] Fehler 1`

My Hostsystem is an actual Debian 11.6 Bullseye (amd64)

**Comment by avaneesh1999** [comment]
The error message you're encountering indicates that the build process is failing because 
it cannot find the qemu-aarch64-static binary in your environment

->Install qemu-user-static Package:
  apt update
  apt install qemu-user-static

->Enable the Binary Emulation:
  update-binfmts --enable qemu-aarch64

->Retry the build
