### ISSUE TITLE
Consider using apt-current in place of install_packages

### ISSUE THREAD

**Issue by alanfranz** [bitnami/minideb#21]
Hello,
I have a small suggestion to improve the image.

When using docker, I had an issue with apt-get which was the same as yours - apt-get lists getting stale, and leaving garbage afterwards, so I created this small, bash-based, public domain tool:

https://github.com/alanfranz/apt-current

apt-current has one additional performance advantage when compared to install_packages: you can choose an "expiry timeout", and ```apt-get update``` is performed only if a) the latest apt-get update was performed more than expiry_timeout seconds ago, or b) if any source file or any apt configuration was changed.

It seems to me that all the binaries used by apt-current are already available in your minideb image.

**Comment by james-w** [comment]
Hi,

Thanks for the suggestion.

The expiry timeout wouldn't help here, as we delete the list files after the run, so there's
no cache to re-use.

Do you think there would be any other advantages to apt-current given that?

Thanks,

James

**Comment by alanfranz** [comment]
Well, you're not forced to delete all the files IMMEDIATELY after reuse, are you? That's a design choice. When using apt-current, I delete downloaded debs immediately (with the right apt-current option), then I do a ```clean-lists``` at the end of the Dockerfile.

That depends on your use case, BTW. When developing new images, I find the apt-current approach very useful, otherwise I need to wait for an apt-get update at EVERY step. This leads to a "massive" ```apt-get install```  (or ```install_packages```) at the beginning, which usually breaks caching (you change the line, you need to rebuild the whole image). On the contrary, with ```apt-current``` you get the best of both world; you don't need to worry about performing dozens of ```apt-get update``` because the lists are always deleted, so you can place the various ```apt-get-current install``` where you actually need them.

BTW, I gave you this info just as a suggestion; for sure, you'll know what you're doing better than I do.

**Comment by james-w** [comment]
Hi,

I appreciate the suggestion, I'm trying to understand what the benefits and tradeoffs would be.

Deleting the apt lists at the end of the Dockerfile doesn't do anything to reduce the image size due
to the way that the docker layers work. The files are still there in the earlier layers, so you don't get
any image size reduction.

Our goal is size reduction, so it is important for us to delete the lists in the same step as they are downloaded. I think that means that apt-current isn't useful for us due to that.

Thanks for your interest in minideb. You have an interesting project there, and it may well be
a better approach than ours. However as we think that we prioritise reduced image sizes we
will stick with our approach for now. We might re-evaluate this decision in future if it becomes
clear that we are prioritising the wrong things.

Thanks,

James

**Comment by alanfranz** [comment]
@james-w 

> Deleting the apt lists at the end of the Dockerfile doesn't do anything to reduce the image size due
> to the way that the docker layers work. The files are still there in the earlier layers, so you don't get
> any image size reduction.

Of course, that's true only if you don't use the ```--squash``` option while building; and when I build "base" images that I want to reuse a lot and update just a little, I make sure to **always build them with squash** (it will, in fact, reduce the total download time). And it seems you're rebuilding the fs from scratch when creating minideb. But of course this may not be true when you're ```using``` minideb downstream, I suppose that's what you mean.

By the way, now you know the possible alternatives, I'm sure you'll pick up whatever you need.

Bye,

Alan
