### ISSUE TITLE
bullseye support

### ISSUE THREAD

**Issue by austriancoder** [bitnami/minideb#77]
Are there any plans to support bullseye? Would you accept a pull request?

**Comment by james-w** [comment]
Hi,

Yes, we should add a bullseye build. A pull request would be welcome.
https://github.com/bitnami/minideb/commit/2c4b4f0f140f6b5ff4b09def2525ecb64978ddb8
likely gives some pointers, though some things have moved around a little since then.
Let me know if you would like any assistance.

Thanks,

James

**Comment by allanadair** [comment]
Any updates on this?

**Comment by austriancoder** [comment]
Not from my side... switched to Debian mini-base.

**Comment by javsalgar** [comment]
cc @juamedgod
