### ISSUE TITLE
CVE-2018-12886 at bitnami/minideb:buster

### ISSUE THREAD

**Issue by rusakovichma** [bitnami/minideb#91]
Hello,

we are using bitnami/minideb:buster image and several SCA Tools (twistlock, clair, snyk) detected CVE-2018-12886 High-severity vulnerability that we are concerned about related to gcc-8 module :
you may see the report at buster image here: https://snyk.io/test/docker/bitnami%2Fminideb%3Abuster#SNYK-DEBIAN10-GCC8-347558
More info about CVE: https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-12886.

Seems that it uses gcc-8 (8.3.0-6) vulnerable package from debian-10 buster release (https://security-tracker.debian.org/tracker/CVE-2018-12886) and there is no fixes or patches is available now from  debian for this CVE. 

How long does it take to apply this patch to minideb image as soon it will be available and how we can know about it?

Thanks

**Comment by beltran-rubo** [comment]
Minideb is rebuilt every day and check if there is a new package available in the Debian repo that is included as part of the image. That means you are able to find a latest version available without "fixable" CVEs in DockerHub registry in a daily basis. 

In that case the CVE is not fixed by Debian. I would strongly suggest to check the details of that issue to know if that is important for your specific case e.g. CVE-2018-12886 only affects binaries for ARM generated with that GCC.

I hope it helps.
